language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
gemfile:
  - gemfiles/ar30.gemfile
  - gemfiles/ar31.gemfile
  - gemfiles/ar32.gemfile
  - gemfiles/ar40.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/ar40.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/ar40.gemfile
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
