language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.2.4
  - jruby-9.0.5.0
  - rbx-2
addons:
  postgresql: "9.4"
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - jruby-9.0.5.0
    - rbx-2
